### ISSUE TITLE
Parse IF operator

### ISSUE THREAD

**Issue by dmarcos89** [denissimon/formula-parser#2]
Hi @denissimon great work!

Any clue on how to parse something like this:
`if(condition;action1;action2)`, `if(condition;action1;if(condition;action1;action2))`, etc?

Thanks

**Comment by denissimon** [comment]
Hi! Thank you.
First off, sorry for the late response, was very, very busy at my work for a company.
As for your question, such conditional expressions are not supported. It’s more related to programming languages than to mathematical formulas. Thus, I think you can try to use PHP "if" statement with combination of Formula Parser library to achieve your goal.
