### ISSUE TITLE
Add more variables

### ISSUE THREAD

**Issue by Meeshalk** [denissimon/formula-parser#4]
Is it possible to add more variables?
If yes, then which letters/characters should not be used?

Very interesting code you have here, 
Thanks

**Comment by denissimon** [comment]
It's possible to do this by using the setValidVariables() method. Please see the examples of the section 4 (Test valid variables) in tests/FormulaParserTest.php
Any letter other than "e" can be used as a variable. The letter "e" is always processed by the parser as a constant = 2.718.

Thank you!
