### ISSUE TITLE
Uninitialized string offset

### ISSUE THREAD

**Issue by vdomah** [denissimon/formula-parser#6]
Hi!
I'm getting this error:
Uninitialized string offset: 2:620 in FormulaParser.
Analyzed the sources but I can't understand why I'm getting this. The formula is x-y+2
Please help, thanks!

**Comment by denissimon** [comment]
Hi! 
What is your PHP version? I cannot reproduce this error at the moment.

**Comment by denissimon** [comment]
Anyways, you can try the following code for the function match1:

``` php
private function match1($matches) {
    $result = $matches[0][0] . '( ( '.substr($matches[0],1,1).' ) )';
    if (isset($matches[0][2])) {
        $result = $result . $matches[0][2];
    }
    return $result;
}
```

Please let me know if it works without any warnings.
