### ISSUE TITLE
Variable error? setValidVariables Doesn't seem to work.

### ISSUE THREAD

**Issue by timothymarois** [denissimon/formula-parser#9]
Hey, so just tried to use this, and based on readme, here is my example, what am I missing? 

```php
      $formula   = '((@variableA + (@variableB * 0.9)) - @variableC)';
        
        try 
        {
            $parser = new FormulaParser($formula, 4);

            $parser->setValidVariables([
                '@variableA','@variableB','@variableC'
            ]);

            $parser->setVariables([
                '@variableA' => 27.99,
                '@variableB' => 23.99,
                '@variableC' => 24.98
            ]);

            $result = $parser->getResult();

            print_r($result);
        } 
        catch (\Exception $e) 
        {
            echo $e->getMessage(), "\n";
        }
```

Results are:

```
Array
(
    [0] => error
    [1] => Variable error
)
```

I can do a formula of `$formula   = '1+1';` and the results are the same. 

It appears setting custom variables outside of the already defined X/Y is not working. at least it won't define new valid variables. 

If I try to set 

```php
$parser->setValidVariables([
       'variablex','variabley'
]);
```

The variable error comes up, even though I'm not even using them.

**Comment by timothymarois** [comment]
It appears, that you're **not allowed to use more than 1 character for variable names**? After testing, I'm able to get any letter to work as a variable, but not an actual variable name. Not good. That should not be a limitation of variable names, that's up to the user/dev to decide what their variables are called. 

I would put this limitation in the readme, and I would highly recommend this gets updated to actual variable naming otherwise, it's useless and I'll just replace the variables in the string myself, not sure what cause you'd limit variable names on the package side.

**Comment by denissimon** [comment]
Hey, any letter other than "e" can be used as a variable. The letter "e" is always processed by the parser as a constant = 2.718. So you can use 25 variables for each formula. Some examples of using `setValidVariables()` can be found in `tests/FormulaParserTest.php`.

You can also use a PHP dictionary and associate letters with names that you like, if this is important to you. Example:
```php
$v = ['myX'=>'x', 'myY'=>'y'];
$result = (new FormulaParser('x+y'))->setVariables([$v['myX'] => 2, $v['myY'] => 3])->getResult()[1]; // 5
```

Thanks for the suggestions, I'll think about it. For now, everything works as expected.
